services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      # - app2
    networks:
      - frontnet

  app1:
    deploy:
      replicas: 5
    build:
      context: ./app1
    # container_name: flask_app1
    # ports:
    #   - "5006-5010"
    environment:
      - DATABASE_URL=mysql://root:password@db/flask_app
    secrets:
      - db-password
    depends_on:
      - db
      # db:
      #   condition: service_healthy
    networks:
      - backnet
      - frontnet ####

  db:
    image: mariadb:latest
    container_name: mysql_db
    #command: '--default-authentication-plugin=mysql_native_password'
    # restart: always
    # healthcheck:
    #   test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
    #   interval: 3s
    #   retries: 5
    #   start_period: 30s
    secrets:
      - db-password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
      #- db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=flask_app
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    # expose:
    #   - 3306
    #   - 33060

    # ports:
    #   - 5000:3306

volumes:
  mysql_data:  # Volume tanımlaması burada
    driver: local
secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
  frontnet:


