name: keycloak_mariadb

services:
  keycl:
    build:
      context: keycl
    #  target: builder
    secrets:
      - db-password
    depends_on:
      db:
        condition: service_healthy
    environment:
      - KC_DB=mariadb
      - KC_DB_URL="jdbc:mariadb://db:3306/example"
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD="$$(cat /run/secrets/db-password)"
      - KC_HOSTNAME=localhost
    ports:
      - "8080:8080"
    volumes:
      # MariaDB JDBC sürücüsünü Keycloak konteynerına kopyalayın
      - ./mariadb-java-client-x.x.x.jar:/opt/jboss/keycloak/standalone/lib/mariadb-java-client.jar
    networks:
      - frontnet
      - backnet


  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mariadb-admin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - type: bind
#        source: ./db/my.cnf
#        target: /etc/mysql/my.cnf
#        read_only: true
     
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
#    expose:
#      - 3306
    ports:
      - 3306:3306
    networks:
      - backnet
  proxy:
    image: nginx
    container_name: nginx
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on: 
      - keycl
    networks:
      - frontnet

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  frontnet:
  backnet:
